### ISSUE TITLE
NoClassDefFoundError in WebStorm 2017.3 (173.2463.22)

### ISSUE THREAD

**Issue by merksam** [jimkyndemeyer/js-graphql-intellij-plugin#103]
Hi! I try to use plugin (version 1.6) with WebStorm 2017.3 (173.2463.22) but have next errors right after start of IDE:
![ide fatal errors 2017-09-25 14-36-11](https://user-images.githubusercontent.com/8118246/30806973-9096387e-a200-11e7-816c-ff3d60d13d51.png)
![ide fatal errors 2017-09-25 14-45-02](https://user-images.githubusercontent.com/8118246/30806937-7261bed2-a200-11e7-9151-0498b617adab.png)

In project directories tree I just see "loading" icon and nothing more. 
![onefile-web-app 5b 7e 2fwork 2fwww 2fonefile 2fweb-app 5d - 2fsrc 2fjs 2fgraphql 2ffragment js 5bonefile-web-app 5d 2017-09-25 14-42-40](https://user-images.githubusercontent.com/8118246/30807004-ac700d90-a200-11e7-8dd7-44684ef02e6e.png)

Also when I get this error in IDE broken "Find by filename" window, it just find nothing when file exists.

**Comment by jimkyndemeyer** [comment]
Hi merksam.

Thanks for reporting this. I've just confirmed that the plugin works with the latest stable WebStorm (2017.2.4), so this appears to only affect the EAP for now.

I'll investigate whether JetBrains intends on removing the Apache commons library.

**Comment by jimkyndemeyer** [comment]
Logged with JetBrains as https://youtrack.jetbrains.com/issue/WEB-28968

**Comment by jimkyndemeyer** [comment]
Fixed with 1.6.1, pending JetBrains approval.

**Comment by jimkyndemeyer** [comment]
Fixed with PR #105
