### ISSUE TITLE
NoClassDefFound issue

### ISSUE THREAD

**Issue by jamespedid** [jimkyndemeyer/js-graphql-intellij-plugin#255]
## Before you create the issue
- Please search the existing issues at https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/issues?q=sort%3Aupdated-desc before opening a new issue.
- Read the FAQ at https://github.com/jimkyndemeyer/js-graphql-intellij-plugin#faq
- If you're using an EAP, try with a stable version. If that works, please mention it in the issue along with both versions.

## Version and Environment Details
__Operation system__: Linux Mint 19.1

__IDE name and version__: WebStorm 2019.1.2

__Plugin version__: 2.10

## Expected Behaviour
In version 2.0.0-end-of-beta, no crash occurs when indexing graphqls files. I would expect this to work in version 2.1.0 as well.

## Actual Behaviour
Webstorm shows an error when indexing files that indicates that a java error has occurred.
Webstorm fails to open when loading graphql file with multiple errors.

```
java.lang.NoClassDefFoundError: graphql/GraphQLException
	at com.intellij.lang.jsgraphql.ide.project.schemastatus.GraphQLConfigSchemaNode.<init>(GraphQLConfigSchemaNode.java:79)
	at com.intellij.lang.jsgraphql.ide.project.schemastatus.GraphQLConfigSchemaNode$GraphQLConfigProjectsNode.lambda$buildChildren$0(GraphQLConfigSchemaNode.java:176)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:545)
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:438)
	at com.intellij.lang.jsgraphql.ide.project.schemastatus.GraphQLConfigSchemaNode$GraphQLConfigProjectsNode.buildChildren(GraphQLConfigSchemaNode.java:177)
	at com.intellij.ui.treeStructure.CachingSimpleNode.getChildren(CachingSimpleNode.java:39)
	at com.intellij.lang.jsgraphql.ide.project.schemastatus.GraphQLSchemasPanel.lambda$null$0(GraphQLSchemasPanel.java:130)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:945)
	at com.intellij.lang.jsgraphql.ide.project.schemastatus.GraphQLSchemasPanel.lambda$null$1(GraphQLSchemasPanel.java:125)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:311)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: graphql.GraphQLException PluginClassLoader[com.intellij.lang.jsgraphql, 2.1.0] com.intellij.ide.plugins.cl.PluginClassLoader@357e20d7
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:51)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 21 more
```

![image](https://user-images.githubusercontent.com/1280555/58247777-71a03780-7d28-11e9-9a1e-a4d2e38b44e9.png)

## Steps to Reproduce / Link to Repo with Reproduction and Instructions
Unsure if this is a code issue or just a dependency issue. May be hard to reproduce.

**Comment by jimkyndemeyer** [comment]
Hi James.

Thanks for using the plugin.

This looks like a local class-loading/distribution issue. I suggest you uninstall the plugin, restart your IDE and reinstall it.

Let me know if that fixes the issue.

Best regards,
Jim.

**Comment by jamespedid** [comment]
I have reinstalled several times previously. It has no effect. Is there a way to determine if the correct java library is being used here?

**Comment by jimkyndemeyer** [comment]
You can compare the plugin directory with the zip file that's available from the 2.1.0 download link at https://plugins.jetbrains.com/plugin/8097-js-graphql/versions

The plugin directory can be found as follows:
- In the help menu, click the "Show log..." menu item
- That opens a folder like `.your-ide-name/system/log`
- Navigate up two levels to the `.your-ide-name` folder
- The plugin is located in `.your-ide-name/config/plugins/JS GraphQL/lib`

You should see a list of jars similar to:

![image](https://user-images.githubusercontent.com/15837712/58378792-35740d80-7f9a-11e9-8416-f45d8326939e.png)

**Comment by jimkyndemeyer** [comment]
Hi James.

I'm resolving this on the basis that I have nothing actionable on it.

Feel free to add comments if you have an update or need additional assistance.

Best regards,
Jim.
